spring:
  application:
    name: NauJava
app:
  name: File Bridge
  version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always