spring:

  application:
    name: NauJava

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

minio:
  url: http://${MINIO_HOST}:${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

  buckets:
    fileBucket:
      name: ${MINIO_FILE_BUCKET}
    reportBucket:
      name: ${MINIO_REPORT_BUCKET}

app:
  name: File Bridge
  version: 1.0

  api:
    base-url: ${API_BASE_URL}

  quotas:
    tariffs:
      BASIC:
        maxStorageSize: 1GB

jwt:
  accessSecret: ${ACCESS_JWT_SECRET}
  refreshSecret: ${REFRESH_JWT_SECRET}
  accessTokenLifetime: 30m
  refreshTokenLifetime: 1d

cookie:
  path: /
  sameSite: Lax
  secure: false
