-- Таблица пользователей
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL,
    role VARCHAR(50) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    storage_quota_id BIGINT NOT NULL UNIQUE
);

-- Таблица квот хранилища
CREATE TABLE storage_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_storage_bytes BIGINT NOT NULL,
    used_storage_bytes BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Таблица статистики файлов
CREATE TABLE file_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    times_downloaded BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    last_downloaded_at TIMESTAMP WITH TIME ZONE
);

-- Таблица файлов
CREATE TABLE files (
    id UUID PRIMARY KEY,
    path TEXT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    expire_at TIMESTAMP WITH TIME ZONE NOT NULL,
    max_downloads INTEGER NOT NULL,
    password_hash TEXT NOT NULL,
    author_id BIGINT,
    statistics_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_files_author FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_files_statistics FOREIGN KEY (statistics_id) REFERENCES file_statistics(id) ON DELETE CASCADE
);

-- Таблица банов пользователей
CREATE TABLE user_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason TEXT NOT NULL,
    banned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    unbanned_at TIMESTAMP WITH TIME ZONE,
    admin_id BIGINT,
    banned_user_id BIGINT,
    CONSTRAINT fk_user_bans_admin FOREIGN KEY (admin_id) REFERENCES users(id),
    CONSTRAINT fk_user_bans_user FOREIGN KEY (banned_user_id) REFERENCES users(id)
);

-- Добавление внешнего ключа для связи User -> StorageQuota (после создания обеих таблиц)
ALTER TABLE users
    ADD CONSTRAINT fk_users_storage_quota
    FOREIGN KEY (storage_quota_id) REFERENCES storage_quotas(id);