create table reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_status VARCHAR(50) NOT NULL,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    generated_at TIMESTAMP WITH TIME ZONE
)